##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-screensaver
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - libdbus-glib-1-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmatekbd-dev
    - libnotify-dev
    - libpam0g-dev
    - libstartup-notification0-dev
    - libsystemd-dev
    - libx11-dev
    - libxext-dev
    - libxss-dev
    - libxt-dev
    - libxxf86vm-dev
    - make
    - mate-common
    - x11proto-scrnsaver-dev
    - x11proto-xext-dev
    - x11proto-xf86vidmode-dev
    - xmlto

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
